dist: trusty
sudo: false
language: c

branches:
  only:
    - master
    - coverity_scan

env:
  global:
    - CMOCKA_INSTALL="$HOME/builds/cmocka-install"
    - CHECKPATCH_INSTALL="$HOME/builds/checkpatch-install"
    - LOGNAME="Travis"
    - secure: "bpdJ8XFtVDkKqecKO+d3fusCDj7Lqk4ArAdwVGvbBBAk1jDztUZQymqiwBmiPf3G6y60PIl40R5BIA8pfA2RvNuTLya54x0n7fGm7AMXyhZCV6zh5JSyvCU2ODgpn7M4MysqfjMye+WgHpiAa1+bgyaJJQD4KyGCnVrFxL2Hg9WDj25fUpEiZnu2bLFn90zOZy2qMKoRh4Z6uTTOrhodS+oUulodOx+YfAU8eTOVlYbSGz2ksJrlO/4t7is56sQ5rAun17UmxzZmQu0YGGyzQSEruz86gRFNJcC5lIa1S48REoTW2/95FuOXAtlw6D6AiiqdHnP9PvFmY6PgefJyG9y+aSHhO4VHCQ5EuFkedGJ1AnSnyNd2d2VzPlrdpUGsZ4F6EvGUGTGfROYEy2IUqsnGuR5muMyzp37qG0XURYhb3T1DrCmdBcVYs6iYGuscnBBKwff3RLemsMwKryI6rY29NfKyM/nR46b71G8wXxfC+AogdUEI4HKZ9x0l4j2le0BDehUGhGl5F2JAaNZfC5xbQMZ/x6ERyyqQRfQmzBFk4Rku7NznJj7+Y616TuF/cgGASRdSG7bjBV75BVa1OPc9kviajEok03hC0gJDDeox+aN2k5n0OPSM2ahEsnfeT2Bp9+moTwNnrNrgXlJLConMpxhAtU4vbAmccWjjb9A="


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; fi
  - gem install mustache

addons:
  coverity_scan:
    project:
      name: "riboseinc/retrace"
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command: "make -j4"
    branch_pattern: coverity_scan

after_failure: cat test/test-suite.log

cache:
  directories:
    - "$CMOCKA_INSTALL"

install:
  - ./ci/install.sh

script:
  - ./ci/main.sh

os:
  - linux
  - osx
